repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
        args: [ "--py38-plus" ]
  - repo: https://github.com/asottile/reorder_python_imports # 导包排序
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        args: [ "--application-directories", "src" ]
  - repo: https://github.com/psf/black # 代码格式化
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8 # 代码风格检查
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # removes UTF-8 byte order marker.
      - id: fix-byte-order-marker
      # Trims trailing whitespace.
      - id: trailing-whitespace
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
